apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    custom.nginx.org/fastcgi: "on"
  name: app-ingress
  namespace: nginx-ingress
spec:
  rules:
  - host: app1.bharat.com
    http:
      paths:
      - backend:
          serviceName: appsvc1
          servicePort: 9000
        path: /
  - host: app2.bharat.com
    http:
      paths:
      - backend:
          serviceName: appsvc2
          servicePort: 9000
        path: /