---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: jenkins
  name: jenkins-ci
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: jenkins-ci
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: jenkins-ci
    spec:
      containers:
      - name: jenkins-server
        image: jenkins/jenkins:lts
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        - containerPort: 50000
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 20
        securityContext: 
          privileged: true
        resources:
          limits:
            cpu: 1
            memory: 4Gi
          requests:
            cpu: 1
            memory: 4Gi
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: DOCKER_HOST
          value: tcp://localhost:2375
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
      - name: dind
        image: docker:18.06-dind
        securityContext:
          privileged: true
        volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
      volumes:
      - name: dind-storage
        hostPath: 
          path: /var/docker-home
      - name: jenkins-home
        hostPath: 
          path: /var/jenkins_home