apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-v1
  labels:
    k8s-app: deployment-v1
  annotations:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: container-httpd
        image: httpd:2.4
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
      restartPolicy: Always
