apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "default-limitrange" 
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "100m" 
        memory: "100Mi" 
      min:
        cpu: "50m" 
        memory: "50Mi" 
    - type: "Container"
      max:
        cpu: "100m" 
        memory: "100Mi" 
      min:
        cpu: "50m" 
        memory: "50Mi" 
      default:
        cpu: "50m" 
        memory: "50Mi" 
      defaultRequest:
        cpu: "50m" 
        memory: "50Mi" 
